default_stages: [commit]
repos:
  # - repo: https://github.com/commitizen-tools/commitizen
  #   rev: v2.29.5
  #   hooks:
  #     - id: commitizen
  #       stages: [commit-msg]
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.74.1
    hooks:
      - id: terraform_fmt
      - id: terraform_validate
      - id: terraform_tflint
      - id: terraform_tfsec
      - id: terraform_checkov
      - id: terraform_docs
    #  - id: terrascan
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: detect-aws-credentials
  - repo: https://github.com/cesar-rodriguez/terrascan
    rev: v0.2.0
    hooks:
    -   id: terrascan
        pass_filenames: false
        args: [-l=terraform] #NOTE: that this is the directory you created earlier to host your terraform
        verbose: true
