name: "Terraform Plan & Apply"

# on:
#   pull_request:

on:
  push:
    branches:
      - 'kevin'

env:
  TF_CLOUD_ORGANIZATION: "kevin-org"
  TF_API_URL: "app.terraform.io"
  TF_API_TOKEN: "${{ secrets.TF_API_TOKEN }}"
  #TF_WORKSPACE: $GITHUB_REF
  CONFIG_DIRECTORY: "./"

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout le code
        uses: actions/checkout@v2

      - name: Set up Terraform CLI
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6  # Modifiez en fonction de la version souhaitée

      - name: Configure Terraform Cloud
        run: |
          echo "credentials \"$TF_API_URL\" {" >> ~/.terraformrc
          echo "  token = \"${{ secrets.TF_API_TOKEN }}\"" >> ~/.terraformrc
          echo "}" >> ~/.terraformrc

      - name: Generate terraform.tf
        run: |
          export WORKSPACE_NAME=$(echo $GITHUB_REF | cut -d / -f 3)
          echo "Nom du workspace: $WORKSPACE_NAME"

          cat <<EOF > terraform.tf 
          terraform {
            cloud {
              organization = "$TF_CLOUD_ORGANIZATION"
              workspaces {
                  name = "$WORKSPACE_NAME"
                  }
              }
              }
          EOF

      - name: Initialize Terraform
        run: terraform init
        
      - name: Terraform plan
        run: |
          terraform plan -out=tfplan
      # - name: Terraform destroy
      #   run: |
      #     terraform destroy --auto-approve
      - name: Terraform apply
        run: |
          terraform apply --auto-approve
